# Generated by Django 2.2.12 on 2021-01-22 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='BuckwheatProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('image', models.URLField(verbose_name='Изображение товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('price_currency', models.CharField(default='грн', max_length=25, verbose_name='Валюта')),
                ('producer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('link_to_shop', models.URLField(verbose_name='Ссылка на магазин')),
                ('link_to_shop_logo', models.URLField(verbose_name='Ссылка на лого магазина')),
                ('weight', models.IntegerField(default='г', verbose_name='Вес в граммах')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
